language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - android-21
    - sys-img-armeabi-v7a-android-21
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
  
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - touch /home/travis/.gradle/gradle.properties
  - echo marvelPrivateKey=\"keyPrivate\" >> /home/travis/.gradle/gradle.properties
  - echo marvelPublicKey=\"keyPublic\" >> /home/travis/.gradle/gradle.properties
  - ./gradlew clean build
  - ./gradlew build connectedCheck
 

